# defaults
image: patkub/docker-make-valgrind
cache:
  untracked: true

########## melangeur ##########

melangeur-build:
  stage: build
  script:
    - cd src
    - make test_melangeur
  artifacts:
    paths:
      - src/test_melangeur

melangeur-test:
  stage: test
  script:
    - valgrind --leak-check=full --error-exitcode=1 src/test_melangeur
  dependencies:
    - melangeur-build

########## tuile ##########

tuile-build:
  stage: build
  script:
    - cd src
    - make test_tuile
  artifacts:
    paths:
      - src/test_tuile

tuile-test:
  stage: test
  script:
    - valgrind --leak-check=full --error-exitcode=1 src/test_tuile
  dependencies:
    - tuile-build

########## plateau ##########

plateau-build:
  stage: build
  script:
    - cd src
    - make test_plateau
  artifacts:
    paths:
      - src/test_plateau

plateau-test:
  stage: test
  script:
    - valgrind --leak-check=full --error-exitcode=1 src/test_plateau
  dependencies:
    - plateau-build

########## liste ##########

list-build:
  stage: build
  script:
    - cd src
    - make test_liste
  artifacts:
    paths:
      - src/test_liste

list-test:
  stage: test
  script:
    - valgrind --leak-check=full --error-exitcode=1 src/test_liste
  dependencies:
    - list-build

